name: food_audit
description: Uses OCR to read composure of food

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.6
  camera: ^0.10.0+4
  path: ^1.8.2
  path_provider: ^2.0.11
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.1
  sliding_up_panel: ^2.0.0+1
  firebase_storage: ^11.0.10
  fl_chart: ^0.55.2
  cached_network_image: ^3.2.3
  html: ^0.15.1
  url_launcher: ^6.1.0
  flutter_native_splash: ^2.2.12
  introduction_screen: ^3.1.4

  #  google_ml_kit:
  #    path: ../
  google_mlkit_commons:
  #    path: ../../google_mlkit_commons
  google_mlkit_image_labeling:
    path: ../../google_mlkit_image_labeling
  google_mlkit_text_recognition:
    path: ../../google_mlkit_text_recognition

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/ml/
    - assets/icons/
    - assets/splash/

flutter_native_splash:
  color: "#698C11"
  image: assets/Icons/splashLog.png
  android: true
  ios: true
  android_12:
    background_image: assets/Icons/splashLog.png
